### ISSUE TITLE
Not a good idea...

### ISSUE THREAD

**Issue by Chiroyce1** [webdev03/meowshield#4]
Just use [Contact Us](https://scratch.mit.edu/contact-us/) to tell the Scratch Team about cloud hijacking instead of intervening on your own... you might also get an alert/banned for using this...

/cc @kccuber-scratch @hello-smile6

**Comment by hello-smile6** [comment]
Should I kill my servers?

**Comment by Chiroyce1** [comment]
> Should I kill my servers?

Yes.

**Comment by hello-smile6** [comment]
Done, can restart them if I have to.

**Comment by hello-smile6** [comment]
Successful, check SA cloud list.

**Comment by hello-smile6** [comment]
@Chiroyce1 They're down! @kccuber-scratch 's should be okay, since they only act when someone knocks it out.

**Comment by hello-smile6** [comment]
See https://replit.com/@kccuber/lets-fix-griffpatchs-cloud-games?v=1

**Comment by webdev03** [comment]
OK

**Comment by webdev03** [comment]
There's nothing that says we could get banned. There will be more and more people coming.

**Comment by webdev03** [comment]
And the ST already knows about cloud hijacking.

**Comment by hello-smile6** [comment]
> There's nothing that says we could get banned. There will be more and more people coming.

So restart? Should we go for centralized DB? I could try to make a Node client.

**Comment by webdev03** [comment]
A node client might be better... I'm not sure though. NPM has better `package-lock` and `package` systems.

**Comment by hello-smile6** [comment]
> A node client might be better... I'm not sure though. NPM has better `package-lock` and `package` systems. Did you know that pnpm is more popular than yarn?

I'd rather use NPM, since it's familiar to me. We'd just have to implement authentication.

**Comment by hello-smile6** [comment]
@webdev03 Just saying, you might want to license under GPLv3, or @LLK might copy your code into one of their backend systems if this works.

**Comment by webdev03** [comment]
That'd actually be nice. No more cloud hackers. Do they have to give credit with MIT?

**Comment by hello-smile6** [comment]
> That'd actually be nice. No more cloud hackers. Do they have to give credit with MIT? If I switch to GPL, I'd use AGPL for more protection.

They need to make it so people can set variables to read-only for anyone but them. Also, people need to learn about zero-trust models.

**Comment by webdev03** [comment]
> Also, people need to learn about zero-trust models.

+1 and github told me to use a reaction

**Comment by hello-smile6** [comment]
> > Also, people need to learn about zero-trust models.
> 
> +1 and github told me to use a reaction

Nice!

**Comment by webdev03** [comment]
You know what fine

**Comment by hello-smile6** [comment]
Shouldn't be an issue. If they ban people, then they won't have access to their accounts anyway, so they'll be able to have nothing but this on their account. Anyway, they're already almost to false bans.

**Comment by webdev03** [comment]
> Anyway, they're already almost to false bans.

![image](https://user-images.githubusercontent.com/75148774/150264701-6a8fb6db-3056-4127-bb6e-7747510ff39c.png)


> they'll be able to have nothing but this on their account

im confused

**Comment by hello-smile6** [comment]
> > Anyway, they're already almost to false bans.
> 
> ![image](https://user-images.githubusercontent.com/75148774/150264701-6a8fb6db-3056-4127-bb6e-7747510ff39c.png)
> 
> > they'll be able to have nothing but this on their account
> 
> im confused

Cloud still works with temp bans.

**Comment by Quantum-Codes** [comment]
Even with perm ban cloud works

**Comment by Quantum-Codes** [comment]
I am seriously saying, better make a repo that detects these attacks reliably, then **manually report in contact us**

**Comment by webdev03** [comment]
ok
